# Generated by Django 4.1.5 on 2023-01-28 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_user_alter_adminuser_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Invalid phone number",
                        regex="^[\\+]?[(]?[0-9]{3}[)]?[-\\s\\.]?[0-9]{3}[-\\s\\.]?[0-9]{4,6}$",
                    )
                ],
            ),
        ),
    ]
