# Generated by Django 4.2b1 on 2023-03-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_user_alter_adminuser_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                ("owner_id", models.IntegerField(primary_key=True, serialize=False)),
                ("money", models.DecimalField(decimal_places=2, max_digits=11)),
            ],
            options={
                "verbose_name": "Bank account",
                "verbose_name_plural": "Bank accounts",
            },
        ),
    ]
