# Generated by Django 4.2b1 on 2023-03-11 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_bankaccount"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankCard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bank_account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app.bankaccount")),
            ],
            options={
                "verbose_name": "Bank card",
                "verbose_name_plural": "Bank cards",
            },
        ),
    ]
