# Generated by Django 4.2b1 on 2023-03-27 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_bankaccount_account_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankaccount",
            name="account_id",
        ),
        migrations.RemoveField(
            model_name="bankaccount",
            name="owner_id",
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="owner",
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to="app.user"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bankcard",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
