# Generated by Django 4.2b1 on 2023-03-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_remove_bankaccount_account_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="friends",
            field=models.ManyToManyField(blank=True, to="app.user"),
        ),
    ]
