# Generated by Django 4.2 on 2023-04-10 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_user_friends"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankcard",
            name="id",
        ),
        migrations.RemoveField(
            model_name="bankcard",
            name="name",
        ),
        migrations.AddField(
            model_name="bankcard",
            name="card_id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=11)),
                (
                    "account_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="account_from", to="app.bankaccount"
                    ),
                ),
                (
                    "account_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="account_to", to="app.bankaccount"
                    ),
                ),
                (
                    "card_from",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_from",
                        to="app.bankcard",
                    ),
                ),
                (
                    "card_to",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_to",
                        to="app.bankcard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
    ]
