# Generated by Django 4.2 on 2023-04-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_remove_bankcard_id_remove_bankcard_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="logged_in",
            field=models.BooleanField(default=False),
        ),
    ]
