# Generated by Django 4.2 on 2023-04-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_user_logged_in"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="logged_in",
        ),
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="friends",
            field=models.ManyToManyField(blank=True, to="app.user"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True),
        ),
    ]
