# Generated by Django 4.2.1 on 2023-05-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_remove_user_logged_in_user_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="has_postcard",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="postcard",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="transaction",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
