image: docker/compose:alpine-1.28.0

stages:
  - lint
  - build
  - deploy.test
  - deploy

before_script:
  - apk add make
  - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  - cp $DOT_ENV $(pwd)/.env

build:
  stage: build
  script:
    - make docker_build docker_push
  tags:
    - job:build
  only:
    - master
    - dev
  environment:
    name: test

lint:
  stage: lint
  script:
    - apk add --no-cache python3 py3-pip
    - pip install isort flake8 black
    - make check_lint
  tags:
    - job:test
  only:
    - master
    - dev
  environment:
    name: test

deploy.test:
  stage: deploy.test
  script:
    - make docker_pull docker_down docker_up docker_migrate
  tags:
    - job:deploy.test
  only:
    - master
  environment:
    name: test

deploy:
  stage: deploy
  script:
    - make docker_pull docker_down docker_up docker_migrate
  tags:
    - job:deploy
  only:
    - dev
  environment:
    name: prod
  when: manual