version: '3.8'
services:
  web:
    build: ./src
    image: django-bot:1
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env

    environment:
      - WAIT_HOSTS=mysql:3306

    ports:
      - 8000:${PORT}

    depends_on:
      - db

  bot:
    build: ./src
    image: django-bot:1
    command: python manage.py run_bot
    env_file:
      - .env

    environment:
      - WAIT_HOSTS:${DB_HOST}:${DB_PORT}

    depends_on:
      - db

  db:
    image: postgres

    environment:
      - WAIT_HOSTS:${DB_HOST}:${DB_PORT}

    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: