version: '3.8'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db

  bot:
    build: .
    command: python manage.py run_bot
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres

    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: